### ISSUE TITLE
xournalpp latex support doesn't work until texlive-latexextra is installed

### ISSUE THREAD

**Issue by 0xdc** [SFTtech/gentoo-overlay#2]
Clicking the Math TeX button in the tool bar pops up a dialog box

```
Could not find the LaTeX package 'standalone'.
Please install standalone (found in texlive-latex-extra) and make sure
it's accessible by your LaTeX installation.
```

Emerging `dev-texlive/texlive-latexextra` fixes the problem. Perhaps this could be added to RDEPEND?

**Comment by TheJJ** [comment]
fixed in ecbee3c813b2cac7d8d12de044f7216222a2cdee, please try the new version. I added `latex` as USE.
