### ISSUE TITLE
net-im/element-desktop's manifest wasn't updated

### ISSUE THREAD

**Issue by realkinetix** [SFTtech/gentoo-overlay#7]
Seems we can't pull sources without the manifest being updated for it.

**Comment by realkinetix** [comment]
ie:
**>>> Fetching (2 of 2) net-im/element-desktop-1.11.19::sft
!!! Fetched file: element-desktop-1.11.19.tar.gz VERIFY FAILED!
!!! Reason: Insufficient data for checksum verification
!!! Got:      
!!! Expected: BLAKE2B BLAKE2S MD5 RMD160 SHA1 SHA256 SHA3_256 SHA3_512 SHA512 WHIRLPOOL
 * Fetch failed for 'net-im/element-desktop-1.11.19'**

**Comment by TheJJ** [comment]
Hmm, strange, my automation seems to have skipped the checksum generation for element-desktop indeed.
Now I've bumped to 1.11.20 where this should be fixed.
But currently it doesn't build for me due to #6 again. Does it build for you?

**Comment by realkinetix** [comment]
It worked for me on my single test case so far - will run the updates on a couple of other machines later today:

```
# equery l element*
 * Searching for element* ...
[I-O] [  ] net-im/element-desktop-1.11.20:0
[I-O] [  ] net-im/element-web-1.11.20:0

```

**Comment by TheJJ** [comment]
ok, then i'll close this until we run into problems again :)
